name: Hello
on: 
   push:
        branches: [main]
jobs: 
     Greet:
           runs-on: ubuntu-latest
           steps: 
                 - uses: /github-actions-practise/.github/workflows
                 - run: echo "hello from gituhub actions"
