name: pr check
on: 
   pull_request:
                branches: [newbranch]
                types:
                      - opened
                      - synchronize
jobs:
     Notify:
            runs-on: ubuntu-latest
            steps:
                  - run: echo "PR check running for the branch ${{ github.ref_name }} "



                  
                      
